<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)^
	    (\s*+
	        (module|class|def
	        |unless|if
	        |case
	        |begin
	        |for|while|until
	        |(  "(\\.|[^"])*+"          # eat a double quoted string
	         | '(\\.|[^'])*+'        # eat a single quoted string
	         |   [^#"']                # eat all but comments and strings
	         )*
	         (                 \s   (do|begin|case)
	         | [-+=&amp;|*/~%^&lt;&gt;~] \s*+ (if|unless)
	         )
	        )\b
	        (?! [^;]*+ ; .*? \bend\b )
	    |(  "(\\.|[^"])*+"              # eat a double quoted string
	     | '(\\.|[^'])*+'            # eat a single quoted string
	     |   [^#"']                    # eat all but comments and strings
	     )*
	     ( \{ (?!  [^}]*+ \} )
	     | \[ (?! [^\]]*+ \] )
	     )
	    ).*$
	|   [#] .*? \(fold\) \s*+ $         # Sune’s special marker
	</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(   (^|;) \s*+ end   \s*+ ([#].*)? $
		|   (^|;) \s*+ end \. .* $
		|   ^     \s*+ [}\]] ,? \s*+ ([#].*)? $
		|   [#] .*? \(end\) \s*+ $    # Sune’s special marker
		|   ^=end
		)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Shoes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(stack|flow)\b</string>
			<key>name</key>
			<string>support.function.slots.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(arrow|fill|nofill|nostroke|line|oval|rect|rotate|shape|star|stroke|strokewidth|transform|translate)\b</string>
			<key>name</key>
			<string>support.function.art.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(animate|background|banner|border|button|caption|check|code|del|dialog|edit_box|edit_line|em|every|image|imagesize|ins|inscription|link|list_box|progress|para|radio|strong|sub|subtitle|sup|tagline|timer|title|video|window)\b</string>
			<key>name</key>
			<string>support.function.elements.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(click|finish|hover|keypress|leave|motion|release|start)\b</string>
			<key>name</key>
			<string>support.function.events.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|after|before|clear|prepend|displace|move|style|toggle)\b</string>
			<key>name</key>
			<string>support.other.manipulation.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gutter|height|hide|left|remove|scroll|scroll_height|scroll_max|scroll_top|show|top|width)\b</string>
			<key>name</key>
			<string>support.type.styles.shoes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(contents|parent)\b</string>
			<key>name</key>
			<string>variable.language.shoes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.shoes</string>
	<key>uuid</key>
	<string>420736C7-1CE0-4976-9984-5B9A0F472697</string>
</dict>
</plist>
